spring.application.name=winz

# Server config
server.address=192.168.0.106
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/winz?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=renu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sharathgoud1717@gmail.com
spring.mail.password=Sh@r@th067

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


