spring.application.name=winz

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/vinz
spring.datasource.username=postgres
spring.datasource.password=renu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Enable PostgreSQL Console-like H2 (not needed for Postgres)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

